### ISSUE TITLE
Metabase as source of inspiration

### ISSUE THREAD

**Issue by dumblob** [arturo-lang/grafito#18]
Just saw [Metabase](https://github.com/metabase/metabase#features ) and thought it might provide some [inspiration](https://www.metabase.com/docs/latest/users-guide/ ) for Grafito :wink:.

Feel free to close this for lack of actionable items (it's meant only as a notification).

**Comment by drkameleon** [comment]
I can see your point! I have been looking into different approaches (whether directly graph-related or not) myself.

Thanks! I'll definitely have a look into it.
