### ISSUE TITLE
Competitor - Grist

### ISSUE THREAD

**Issue by dumblob** [arturo-lang/grafito#20]
If you haven't heard of [Grist](https://github.com/gristlabs/grist-core/ ) yet, I can only advice to take a look at.

It's getting closer and closer to my vision of a simple DB for my use cases.

It's built around a sophisticated model of permissions and roles which is what I was always looking for. But with a simple to use interface not trying to hide anything:

https://support.getgrist.com/access-rules/

It's also fully built around newest Python, so all expressions are Python, all conditions etc. in rules are pure python scripts.

It also nicely solves the problem of data types by allowing one to seamlessly integrate custom widgets (with both read & write capabilities). But there's more - the API is built around the **live** principle - so shown data are automatically reflecting the current state of the changes in the backend DB (i.e. reactive programming with automated 0-effort persistency). Hopefully [fully custom widget **stack**](https://github.com/gristlabs/grist-core/issues/161 ) will become true at some point.

To me it seems it's a strong "competition" to Grafito. And I think it's good to have a competitor - you can learn a lot which saves a lot of work and accelerates innovation.

**Comment by drkameleon** [comment]
This looks definitely interesting! I *will* have a look into it. 

Any inspiration is more than valuable.

Thanks! 😉
